# -*- coding: utf-8 -*-
"""IS547 Course Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zxg5x4qqAiRjebronKPP1wpJZOq_17uc
"""

import pandas as pd

input_file = "Climate Dataset1.csv"
output_file = "ghcn_illinois_clean.csv"

stations = [
    "USW00094846", "USW00014819", "USW00014880", "USW00014923",
    "USW00014842", "USW00094870", "USW00003887", "USW00014834",
    "USW00013802", "USW00094822"
]

station_info = {
    "USW00094846": ("Chicago O'Hare Intl AP", "North"),
    "USW00014819": ("Chicago Midway AP", "North"),
    "USW00014880": ("Chicago Waukegan Rgnl AP", "North"),
    "USW00014923": ("Moline Quad City Intl AP", "Northwest"),
    "USW00014842": ("Peoria General Wayne A Downing Intl AP", "Central"),
    "USW00094870": ("Champaign Urbana Willard AP", "Central"),
    "USW00003887": ("Decatur AP", "Central"),
    "USW00014834": ("Joliet", "North-Central"),
    "USW00013802": ("Belleville SIU Rsch", "Southwest"),
    "USW00094822": ("Rockford Greater Rockford AP", "North")
}

print("Starting full curation pipeline...")

df = pd.read_csv(
    input_file,
    quotechar='"',
    on_bad_lines='skip',
    low_memory=False
)

print(f"Original rows: {len(df):,}")

# Filtering stations
df = df[df["STATION"].isin(stations)].copy()

# Safe column selection
keep_cols = ["STATION", "NAME", "DATE", "TMAX", "TMIN", "TAVG",
             "PRCP", "SNOW", "SNWD",
             "TMAX_ATTRIBUTES", "TMIN_ATTRIBUTES", "TAVG_ATTRIBUTES",
             "PRCP_ATTRIBUTES", "SNOW_ATTRIBUTES", "SNWD_ATTRIBUTES"]
keep_cols = [col for col in keep_cols if col in df.columns]
df = df[keep_cols].copy()

# Converting date
df["DATE"] = pd.to_datetime(df["DATE"], errors="coerce")

# Handling trace precipitation
# 'T' = trace → treated as 0 for consistency
for col in ["PRCP", "SNOW", "SNWD"]:
    if col in df.columns:
        df[col] = df[col].astype(str).str.replace("T", "0", regex=False)

# Converting all numeric columns
for col in ["TMAX", "TMIN", "TAVG", "PRCP", "SNOW", "SNWD"]:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors="coerce")

# Droping rows with no temperature data
df = df.dropna(subset=["TMAX", "TMIN"], how="all")

# Removing duplicates
df = df.drop_duplicates(subset=["STATION", "DATE"])

temp_cols = [col for col in ["TMAX", "TMIN", "TAVG"] if col in df.columns]
precip_cols = [col for col in ["PRCP", "SNOW", "SNWD"] if col in df.columns]
df[temp_cols] = df[temp_cols] / 10.0
df[precip_cols] = df[precip_cols] / 10.0

# NOAA TAVG is inconsistent → recomputing if missing
df["TAVG"] = df["TAVG"].fillna((df["TMAX"] + df["TMIN"]) / 2)

print("\nData ranges after unit conversion:")
print(df[["TMAX", "TMIN", "TAVG", "PRCP", "SNOW"]].describe().round(2))

df = df[(df["TMAX"] < 60) & (df["TMIN"] > -50)]

# Flags reviewed but not used to preserve completeness
attr_cols = [col for col in df.columns if "ATTRIBUTES" in col]
df = df.drop(columns=attr_cols)

# Safe mapping
df["STATION_NAME"] = df["STATION"].map(lambda x: station_info.get(x, ("Unknown", "Unknown"))[0])
df["REGION"] = df["STATION"].map(lambda x: station_info.get(x, ("Unknown", "Unknown"))[1])

# Checking for mapping issues
if df["STATION_NAME"].isin(["Unknown"]).any():
    print("Warning: Some stations not mapped correctly")

# Adding time features
df["YEAR"] = df["DATE"].dt.year
df["MONTH"] = df["DATE"].dt.month

# Cleaner season logic
def get_season(month):
    if month in [12, 1, 2]:
        return "Winter"
    elif month in [3, 4, 5]:
        return "Spring"
    elif month in [6, 7, 8]:
        return "Summer"
    else:
        return "Fall"

df["SEASON"] = df["MONTH"].apply(get_season)

final_cols = ["STATION", "STATION_NAME", "REGION", "DATE", "YEAR", "MONTH", "SEASON",
              "TMAX", "TMIN", "TAVG", "PRCP", "SNOW", "SNWD"]
final_cols = [col for col in final_cols if col in df.columns]
df = df[final_cols].copy()

df = df.sort_values(["STATION", "DATE"]).reset_index(drop=True)

print(f"\nFinal cleaned rows: {len(df):,}")
print(df.head())

df.to_csv(output_file, index=False)
print(f"\nSaved clean, curated dataset → {output_file}")
print(" Includes: region + season + validated units (ready for integration)")

import pandas as pd
import glob

from google.colab import drive
drive.mount('/content/drive')

input_path = "/content/drive/MyDrive/StormEvents_details/*.csv"   # folder containing all years
output_file = "storm_events_all_clean.csv"

event_types = ["Winter Storm", "Blizzard", "Flood", "Excessive Heat"]

print("Starting multi-year Storm Events cleaning...")

files = glob.glob(input_path)

all_data = []

for file in files:
    print(f"\nProcessing: {file}")

    df = pd.read_csv(file, low_memory=False)

    # Filtering Illinois
    df = df[df["STATE"] == "ILLINOIS"].copy()

    # Filtering event types
    df = df[df["EVENT_TYPE"].isin(event_types)].copy()

    # Selecting columns
    keep_cols = [
        "STATE", "CZ_NAME", "EVENT_TYPE",
        "BEGIN_DATE_TIME", "END_DATE_TIME",
        "DAMAGE_PROPERTY", "DAMAGE_CROPS",
        "INJURIES_DIRECT", "DEATHS_DIRECT"
    ]

    keep_cols = [col for col in keep_cols if col in df.columns]
    df = df[keep_cols].copy()

    # Cleaning dates
    df["BEGIN_DATE_TIME"] = pd.to_datetime(df["BEGIN_DATE_TIME"], errors="coerce")
    df["END_DATE_TIME"] = pd.to_datetime(df["END_DATE_TIME"], errors="coerce")

    df = df.dropna(subset=["BEGIN_DATE_TIME", "END_DATE_TIME"])

    # Parsing damage
    def parse_damage(val):
        if pd.isna(val):
            return 0
        val = str(val).strip()
        if val == "" or val == "0":
            return 0

        multiplier = 1
        if val.endswith("K"):
            multiplier = 1_000
            val = val[:-1]
        elif val.endswith("M"):
            multiplier = 1_000_000
            val = val[:-1]
        elif val.endswith("B"):
            multiplier = 1_000_000_000
            val = val[:-1]

        try:
            return float(val) * multiplier
        except:
            return 0

    df["DAMAGE_PROPERTY"] = df["DAMAGE_PROPERTY"].apply(parse_damage)
    df["DAMAGE_CROPS"] = df["DAMAGE_CROPS"].apply(parse_damage)

    rows = []

    for _, row in df.iterrows():
        start = row["BEGIN_DATE_TIME"].date()
        end = row["END_DATE_TIME"].date()

        date_range = pd.date_range(start=start, end=end)

        for d in date_range:
            rows.append({
                "STATE": row["STATE"],
                "COUNTY": row["CZ_NAME"],
                "DATE": d,
                "EVENT_TYPE": row["EVENT_TYPE"],
                "DAMAGE_PROPERTY": row["DAMAGE_PROPERTY"],
                "DAMAGE_CROPS": row["DAMAGE_CROPS"],
                "INJURIES": row["INJURIES_DIRECT"],
                "DEATHS": row["DEATHS_DIRECT"]
            })

    df_daily = pd.DataFrame(rows)

    all_data.append(df_daily)

# Combining all years' files
print("\nCombining all years...")
final_df = pd.concat(all_data, ignore_index=True)

final_df["EVENT_FLAG"] = 1

final_df = final_df.groupby(
    ["STATE", "COUNTY", "DATE", "EVENT_TYPE"],
    as_index=False
).agg({
    "EVENT_FLAG": "max",
    "DAMAGE_PROPERTY": "sum",
    "DAMAGE_CROPS": "sum",
    "INJURIES": "sum",
    "DEATHS": "sum"
})

final_df = final_df.sort_values(["COUNTY", "DATE"])

print(f"Final dataset rows: {len(final_df):,}")
print(final_df.head())

final_df.to_csv(output_file, index=False)

print(f"\nSaved → {output_file}")
print("   Includes ALL years (2010–2025)")

import pandas as pd

# Loading cleaned GHCN file
df_ghcn = pd.read_csv("ghcn_illinois_clean.csv")

# Station → County mapping
station_to_county = {
    "USW00094846": "Cook",      # Chicago O'Hare
    "USW00014819": "Cook",      # Chicago Midway
    "USW00014880": "Lake",      # Waukegan
    "USW00094822": "Winnebago", # Rockford
    "USW00014923": "Rock Island", # Moline
    "USW00014842": "Peoria",    # Peoria
    "USW00094870": "Champaign", # Champaign-Urbana
    "USW00003887": "Macon",     # Decatur
    "USW00014834": "Will",      # Joliet
    "USW00013802": "St. Clair"  # Belleville
}

df_ghcn["COUNTY"] = df_ghcn["STATION"].map(station_to_county)

# Saving the updated file
df_ghcn.to_csv("ghcn_illinois_clean_with_county.csv", index=False)

print("Added COUNTY column!")
print(df_ghcn[["STATION", "STATION_NAME", "REGION", "COUNTY"]].drop_duplicates())

import pandas as pd

ghcn = pd.read_csv("ghcn_illinois_clean_with_county.csv")
storm = pd.read_csv("storm_events_all_clean.csv")

print(f"GHCN rows: {len(ghcn):,}")
print(f"Storm rows: {len(storm):,}")

# Making sure DATE columns are datetime
ghcn["DATE"] = pd.to_datetime(ghcn["DATE"])
storm["DATE"] = pd.to_datetime(storm["DATE"])

# Left join: keeping all weather days and add storm events when they exist
merged = ghcn.merge(
    storm,
    on=["DATE", "COUNTY"],
    how="left"
)

# Filling missing event data with 0/None
merged["EVENT_FLAG"] = merged["EVENT_FLAG"].fillna(0).astype(int)
merged["DAMAGE_PROPERTY"] = merged["DAMAGE_PROPERTY"].fillna(0)
merged["DAMAGE_CROPS"]    = merged["DAMAGE_CROPS"].fillna(0)
merged["INJURIES"]        = merged["INJURIES"].fillna(0)
merged["DEATHS"]          = merged["DEATHS"].fillna(0)

# If no event on that day, set EVENT_TYPE to "None"
merged["EVENT_TYPE"] = merged["EVENT_TYPE"].fillna("No Event")

print(f"\nMerged dataset rows: {len(merged):,}")
print(merged[["DATE", "COUNTY", "REGION", "EVENT_TYPE", "DAMAGE_PROPERTY", "TMAX", "PRCP"]].head(10))

merged.to_csv("final_integrated_illinois_climate_events.csv", index=False)

print("\nSaved final integrated file → final_integrated_illinois_climate_events.csv")
print("   Ready for analysis and your final report!")